package e

const (
	API_KEY2                      = "SJN5BSUXRVEMG436AKUDP547IBGV5HWHFB"
	API_KEY3                      = "F3RJGNISMQ25PCTXZIKJUAZI266NM5UJPC"
	API_KEY4                      = "NJZTAMIQEYZMV7NEQTEDPCKGR5FV4A4EXI"
)

